name: nyc-citibike-pipeline

schedule: "0 0 15 * *"

start_date: 2024-02-15

default_connections:
  google_cloud_platform: nyc_citibike

# TODO: Define pipeline variables using JSON Schema and defaults.
# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
# variables:
#   taxi_types:
#     type: TODO  # should be: array
#     items:
#       type: TODO  # should be: string
#     default: TODO  # e.g. ["yellow", "green"]
